[package]
name = "impossible-bosses"
version = "0.1.4"
authors = ["Lipen <lipen00@gmail.com>"]

[dependencies.sfml]
path = "C:/Data/Programming/Rust/rust-sfml"
# git = "https://github.com/jeremyletang/rust-sfml"
# version = "0.11.2"
