[package]
name = "impossible-bosses"
version = "0.1.1"
authors = ["Lipen <lipen00@gmail.com>"]

# [dependencies]
# sfml = "0.11.2"

[dependencies.sfml]
path = "C:/Data/Programming/Rust/rust-sfml"
# git = "https://github.com/jeremyletang/rust-sfml"
